<?php /* @var $this EcomDev_Sphinx_Block_Layer */ ?>
<?php if (!$this->getRequest()->isXmlHttpRequest()): ?>
<script type="text/javascript">
window.ecomdevSphinxDelayed = function (callback) {
    if (window.EcomDev && window.EcomDev.Sphinx) {
        callback();
    } else {
        setTimeout(function () { ecomdevSphinxDelayed(callback); }, 2);
    }
};
</script>
<?php endif;?>
<?php if ($this->getFacets()): ?>
<div class="block block-layered-nav">
    <div class="block-title">
        <strong><span><?php echo $this->__('Shop By') ?></span></strong>
    </div>
    <div class="block-content toggle-content">
        <p class="block-subtitle block-subtitle--filter"><?php echo $this->__('Filter') ?></p>
        <dl id="narrow-by-list">
        <?php foreach ($this->getFacets() as $_facet): ?>
            <?php $_render = $this->getRenderer($_facet); ?>
            <?php if ($_render->isVisible($_facet)): ?>
            <?php echo $_render->render($_facet); ?>
            <?php endif; ?>
        <?php endforeach; ?>
        </dl>
        <script type="text/javascript">decorateDataList('narrow-by-list')</script>
    </div>
</div>
<?php endif;?>
<?php if (!$this->getRequest()->isXmlHttpRequest()): ?>
<script type="text/javascript">
    ecomdevSphinxDelayed(function () {
        window.sphinxLayer = new EcomDev.Sphinx.Layer(
            '.product-ajax-link',
            'div.block-layered-nav',
            'div.category-products',
            true
        );
    });
</script>
<?php endif; ?>
