<?php /* @var $this EcomDev_Sphinx_Block_Layer_Facet_Renderer_Slider */ ?>
<dt><?php echo $this->getLabel() ?><?php if ($this->isSelected($this->getFacet())):?><a class="product-ajax-link col-right" href="<?php echo $this->getClearUrl($this->getFacet());?>"><?php echo $this->__('Clear');?></a><?php endif; ?></dt>
<dd id="<?php echo $this->getHtmlId();?>">
    <ul>
        <li class="slider-container">
            <div id="<?php echo $this->getHtmlId();?>-slider"></div>
        </li>
    </ul>
    <script type="text/javascript">
        ecomdevSphinxDelayed(function () {
            new EcomDev.Sphinx.Slider('<?php echo $this->getHtmlId();?>-slider', <?php echo $this->getOptionJson();?>);
        });
    </script>
</dd>
