я<?php /* @var $this EcomDev_Sphinx_Block_Layer_Facet_Renderer_Slider */ ?>
<dt><?php echo $this->getLabel() ?></dt>
<dd>
    <ul>
        <li>Slider Min Value: <?php echo $this->getMinimumValue();?> </li>
        <li>Slider Max Value: <?php echo $this->getMaximumValue();?> </li>
        <?php if ($this->isSelected($this->getFacet())): ?>
        <li>Slider Current Start Value: <?php echo $this->getCurrentStartValue();?> </li>
        <li>Slider Current End Value: <?php echo $this->getCurrentEndValue();?> </li>
        <?php endif; ?>
        <li>Slider Url: <?php echo $this->getValueUrl();?> </li>
    </ul>
</dd>
